export const VECTOR = {
  apple: require('./apple.png'),
  user: require('./user.png'),
  arrow: require('./arrow.png'),
  chart: require('./chart.png'),
  house: require('./house.jpg'),
  client: require('./client.png'),
  ggl: require('./gg.png'),
  fb: require('./fb.png'),
  hmIcon: require('./home.png'),
  logo: require('./logo.png'),
  self: require('./me.jpg'),
  pdf: require('./pdf.png'),
  ppt: require('./ppt.png'),
  property: require('./property.png'),
  me: require('./me.jpg'),
  base: require('./Base-Avatar.png'),
  Photo1: require('./Photo1.png'),
  Photo2: require('./Photo2.png'),
  Photo3: require('./Photo3.png'),
  Photo4: require('./Photo4.png'),
  thumb: require('./thumb.png'),
};
